
FUNCTION(DETERMINE_OGRE_THREAD_PROVIDER _tp_var _file)
  IF(EXISTS ${_file})
    FILE(READ ${_file} _file_content)
    SET(_parts ${ARGN})
    LIST(LENGTH _parts _parts_length)
    IF(NOT ${_parts_length} EQUAL 3)
      SET(_parts MAJOR MINOR PATCH)
    ENDIF()

    FOREACH(_part ${_parts})
      STRING(REGEX MATCH "#define OGRE_THREAD_PROVIDER +([0-9]+)" _match ${_file_content})
      IF(_match)
        SET(${_tp_var} ${CMAKE_MATCH_1})
        SET(${_tp_var} ${CMAKE_MATCH_1} PARENT_SCOPE)
      ELSE()
        SET(${_tp_var} "0")
        SET(${_tp_var} "0" PARENT_SCOPE)
      ENDIF()
    ENDFOREACH(_part)
    SET(${_tp_var}_VERSION "${${_tp_var}_VERSION}" PARENT_SCOPE)
  ENDIF(EXISTS ${_file})
ENDFUNCTION(DETERMINE_OGRE_THREAD_PROVIDER)
