# - Find CEGUIOGRE includes and library
#
# This module defines
#  CEGUIOGRE_INCLUDE_DIRS
#  CEGUIOGRE_LIBRARIES, the libraries to link against to use CEGUIOGRE.
#  CEGUIOGRE_LIBRARY_DIRS, the location of the libraries
#  CEGUIOGRE_FOUND, If false, do not try to use CEGUIOGRE
#
# Copyright © 2007-2008, Matt Williams
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

IF (CEGUIOGRE_LIBRARIES AND CEGUIOGRE_INCLUDE_DIRS)
	SET(CEGUIOGRE_FIND_QUIETLY TRUE)
ENDIF (CEGUIOGRE_LIBRARIES AND CEGUIOGRE_INCLUDE_DIRS)

#SET(OGRESDK $ENV{OGRE_HOME})
#STRING(REGEX REPLACE "[\\]" "/" OGRESDK "${OGRESDK}")
FILE(TO_CMAKE_PATH "$ENV{OGRE_HOME}" OGRESDK)
SET(CEGUIOGRE_INCLUDE_SEARCH_DIRS
	${INCLUDE_SEARCH_DIRS}
	${CMAKE_LIBRARY_PATH}
	/usr/include/OGRE
	/usr/local/include/OGRE
	/opt/include/OGRE
	/opt/OGRE/include
	$ENV{OGRE_HOME}/samples/include
	$ENV{OGRE_HOME}/Samples/Common/CEGUIRenderer/include
	CACHE STRING ""
)

SET(CEGUIOGRE_LIBRARY_SEARCH_DIRS
	${LIBRARY_SEARCH_DIRS}
	${CMAKE_LIBRARY_PATH}
	/usr/lib
	/usr/lib64
	/usr/local/lib
	/usr/local/lib64
	/opt/lib
	/opt/lib64
	/opt/OGRE/lib
	/opt/OGRE/lib64
	$ENV{OGRE_HOME}/lib
	$ENV{OGRE_HOME}/lib64
	CACHE STRING ""
)

IF (WIN32) #Windows
	MESSAGE(STATUS "Looking for CEGUIOGRE")
	FIND_PATH(CEGUIOGRE_INCLUDE_DIRS Ogre.h ${CEGUIOGRE_INCLUDE_SEARCH_DIRS})
	FIND_LIBRARY(CEGUIOGRE_LIBRARIES debug OgreGUIRenderer_d optimized OgreGUIRenderer PATHS ${CEGUIOGRE_LIBRARY_SEARCH_DIRS})

# 	SET(OGRESOURCE $ENV{OGRE_NEW})
# 	IF (OGRESDK)
# 		MESSAGE(STATUS "Using CEGUIOGRE from OGRE SDK")
# 		SET(OGRESDK $ENV{OGRE_HOME})
# 		STRING(REGEX REPLACE "[\\]" "/" OGRESDK "${OGRESDK}")
# 		SET(CEGUIOGRE_INCLUDE_DIRS ${OGRESDK}/samples/include)
# 		SET(CEGUIOGRE_LIBRARY_DIRS ${OGRESDK}/lib)
# 		SET(CEGUIOGRE_LIBRARIES debug OgreGUIRenderer_d optimized OgreGUIRenderer)
# 	ELSEIF (OGRESOURCE)
# 		MESSAGE(STATUS "Using CEGUIOGRE from OGRE Source")
# 		SET(CEGUIOGRE_INCLUDE_DIRS C:/ogrenew/Samples/Common/CEGUIRenderer/include)
# 		SET(CEGUIOGRE_LIBRARY_DIRS ${OGRESDK}/lib)
# 		SET(CEGUIOGRE_LIBRARIES debug OgreGUIRenderer_d optimized OgreGUIRenderer)
# 	ELSE (OGRESDK)
# 		IF (NOT DEPENDENCIES_PATH)
# 			MESSAGE(STATUS "Please set DEPENDENCIES_PATH (the directory containing 'common' and 'dependencies')")
# 		ELSE (NOT DEPENDENCIES_PATH)
# 			SET(CEGUIOGRE_INCLUDE_DIRS ${DEPENDENCIES_PATH}/dependencies/Ogre/CEGUI)
# 			SET(CEGUIOGRE_LIBRARIES optimized OgreGUIRenderer debug OgreGUIRenderer_d)
# 			SET(CEGUIOGRE_LIBRARY_DIRS optimized ${DEPENDENCIES_PATH}/dependencies/lib/release debug ${DEPENDENCIES_PATH}/dependencies/lib/debug)
# 		ENDIF (NOT DEPENDENCIES_PATH)
# 	ENDIF (OGRESDK)
ELSE (WIN32) #Unix/OSX
	CMAKE_MINIMUM_REQUIRED(VERSION 2.4.7 FATAL_ERROR)
	FIND_PACKAGE(PkgConfig)
	IF(PKG_CONFIG_FOUND)
		PKG_SEARCH_MODULE(CEGUIOGRE CEGUI-OGRE)
		SET(CEGUIOGRE_INCLUDE_DIRS ${CEGUIOGRE_INCLUDE_DIRS})
		SET(CEGUIOGRE_LIBRARY_DIRS ${CEGUIOGRE_LIBDIR})
		SET(CEGUIOGRE_LIBRARIES ${CEGUIOGRE_LIBRARIES} CACHE STRING "")
	ENDIF(PKG_CONFIG_FOUND)
	IF(NOT CEGUIOGRE_FOUND) #If PkgConfig couldn't find OGRE...
		IF (NOT CEGUIOGRE_FIND_QUIETLY)
			MESSAGE(STATUS " Manually searching for CEGUIOGRE")
		ENDIF (NOT CEGUIOGRE_FIND_QUIETLY)
		FIND_PATH(CEGUIOGRE_INCLUDE_DIRS Ogre.h ${CEGUIOGRE_INCLUDE_SEARCH_DIRS})
		FIND_LIBRARY(CEGUIOGRE_LIBRARIES OgreMain PATHS ${CEGUIOGRE_LIBRARY_SEARCH_DIRS})
	ENDIF(NOT CEGUIOGRE_FOUND)
ENDIF (WIN32)

#Do some preparation
SEPARATE_ARGUMENTS(CEGUIOGRE_INCLUDE_DIRS)
SEPARATE_ARGUMENTS(CEGUIOGRE_LIBRARIES)

SET(CEGUIOGRE_INCLUDE_DIRS ${CEGUIOGRE_INCLUDE_DIRS})
SET(CEGUIOGRE_LIBRARIES ${CEGUIOGRE_LIBRARIES})
SET(CEGUIOGRE_LIBRARY_DIRS ${CEGUIOGRE_LIBRARY_DIRS})

MARK_AS_ADVANCED(CEGUIOGRE_INCLUDE_DIRS CEGUIOGRE_LIBRARIES CEGUIOGRE_LIBRARY_DIRS)

IF (CEGUIOGRE_INCLUDE_DIRS AND CEGUIOGRE_LIBRARIES)
	SET(CEGUIOGRE_FOUND TRUE)
ENDIF (CEGUIOGRE_INCLUDE_DIRS AND CEGUIOGRE_LIBRARIES)

IF (CEGUIOGRE_FOUND)
	IF (NOT CEGUIOGRE_FIND_QUIETLY)
		MESSAGE(STATUS "  libraries : ${CEGUIOGRE_LIBRARIES} from ${CEGUIOGRE_LIBRARY_DIRS}")
		MESSAGE(STATUS "  includes  : ${CEGUIOGRE_INCLUDE_DIRS}")
	ENDIF (NOT CEGUIOGRE_FIND_QUIETLY)
ELSE (CEGUIOGRE_FOUND)
	IF (CEGUIOGRE_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find CEGUIOGRE. Make sure you have the CEGIOOGRE development headers installed. They should be part of OGRE. Otherwise, try setting LIBRARY_SEARCH_DIRS and INCLUDE_SEARCH_DIRS to the place CEGUIOGRE was installed with -DLIBRARY_SEARCH_DIRS=<path/to/lib> -DINCLUDE_SEARCH_DIRS=<path/to/include>")
	ENDIF (CEGUIOGRE_FIND_REQUIRED)
ENDIF (CEGUIOGRE_FOUND)
