
CC = g++ -fPIC

LIBS = -lpthread -lm

INCLUDE = $(BASE_DIR)/speex-1.1.4/libspeex/ -I$(BASE_DIR)/Include -I$(BASE_DIR)/Include/RakVoice

#uncoment the second 'DEBUG' to enable debuging.
#DEBUG =
DEBUG = -ggdb

SPEEX_DIR = $(BASE_DIR)/speex-1.1.4/libspeex/

VERSION = 2.0.13

LIBS_DIR = /usr/lib

INCLUDE_DIR = /usr/include

PWD = `pwd`
