system CastHealParty
{
    category                                    Sumwars
    technique 
    {
        material                                heal_particle
        default_particle_width                  0.4
        default_particle_height                 0.4
        default_particle_depth                  0.308824
        renderer                                Billboard
        {
        }
        emitter                                 SphereSurface 
        {
            emission_rate                       50
            angle                               180
            velocity                            dyn_random
            {
                min                             5
                max                             20
            }
            particle_width                      4
            particle_height                     4
            start_colour_range                  1 0 0 1
            end_colour_range                    1 0.141176 0.141176 1
            radius                              1
        }
        affector                                Colour Affector58
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.143478  1 1 1 1
            time_colour                         0.782609  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                LinearForce Affector71
        {
            mass_affector                       200
            force_vector                        0 -10 0
        }
        affector                                TextureRotator Affector14
        {
            rotation                            2
            rotation_speed                      1
        }
    }
}
