system CastHeal
{
    category                                    Sumwars
    technique 
    {
        material                                heal_particle
        default_particle_width                  0.3
        default_particle_height                 0.3
        default_particle_depth                  0.3
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       40
            angle                               25
            time_to_live                        2
            velocity                            3
            start_colour_range                  1 0 0 1
            end_colour_range                    1 0.101961 0.101961 1
            colour                              1 0.0588235 0.0588235 1
        }
        affector                                Colour Affector4
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.143478  1 1 1 1
            time_colour                         0.71087  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                TextureRotator Affector1
        {
            rotation                            dyn_random
            {
                min                             0
                max                             2
            }
            rotation_speed                      0.5
        }
        affector                                LinearForce Affector2
        {
            force_vector                        0 -4 0
        }
    }
}
