system FireAura
{
    category                                    Sumwars
    technique 
    {
        visual_particle_quota                   1
        material                                Aureola
        default_particle_width                  6
        default_particle_height                 6
        default_particle_depth                  6
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            velocity                            dyn_random
            {
                min                             0.6
                max                             1.6
            }
            position                            0 0.2 0
            start_colour_range                  0.8 0.1 0.1 1
            end_colour_range                    0.6 0.5 0.1 1
        }
        affector                                LinearForce 
        {
            force_vector                        0 1.4 0
        }
        affector                                TextureRotator Affector6
        {
            rotation_speed                      2
        }
        affector                                Colour Affector7
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.597826  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
}
