system Firewall
{
    category                                    Sumwars
    technique 
    {
        material                                fire_particle
        default_particle_width                  1
        default_particle_height                 1
        default_particle_depth                  1
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       dyn_random
            {
                min                             180
                max                             200
            }
            angle                               15
            time_to_live                        dyn_random
            {
                min                             2
                max                             3
            }
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            box_width                           0.6
            box_height                          0.6
            box_depth                           0.6
        }
        affector                                Colour Affector0
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.152174  1 1 1 1
            time_colour                         0.382609  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
}
