system Fire_Explosion
{
    category                                    Sumwars
    technique Fireball
    {
        material                                fire_particle_cloud
        default_particle_width                  1.5
        default_particle_height                 1.5
        default_particle_depth                  1.5
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       30
            angle                               360
            time_to_live                        0.35
            velocity                            3
            duration                            0.5
            start_colour_range                  1 0 0 1
            end_colour_range                    0.5 0.5 0 1
        }
        affector                                Scale Affector296
        {
            xyz_scale                           2
            since_start_system                  true
        }
        affector                                Scale 
        {
        }
        affector                                Colour Affector314
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.154348  1 1 1 1
            time_colour                         0.558696  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                TextureRotator Affector315
        {
            rotation                            dyn_random
            {
                min                             0
                max                             3
            }
            rotation_speed                      2
        }
    }
    technique Smoke
    {
        material                                SmokeSprite
        renderer                                Billboard
        {
            texture_coords_rows                 5
            texture_coords_columns              6
        }
        emitter                                 Point Emitter115
        {
            emission_rate                       20
            angle                               360
            time_to_live                        1
            velocity                            2
            duration                            0.5
            particle_width                      3
            particle_height                     3
            particle_depth                      3
        }
        affector                                Colour Affector182
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.265217  1 1 1 1
            time_colour                         0.717391  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                Scale Affector201
        {
            xyz_scale                           3
        }
        affector                                LinearForce Affector225
        {
            force_vector                        0 5 0
        }
    }
    technique Sparks
    {
        material                                Flare
        renderer                                Billboard
        {
        }
        emitter                                 Point Emitter195
        {
            emission_rate                       100
            angle                               90
            time_to_live                        0.4
            velocity                            30
            duration                            0.1
            particle_width                      0.5
            particle_height                     0.5
            particle_depth                      0.5
            start_colour_range                  1 0 0 1
            end_colour_range                    0.5 0.5 0 1
        }
        affector                                LinearForce Affector317
        {
            force_vector                        0 -15 0
        }
        affector                                ScaleVelocity Affector318
        {
        }
        affector                                Colour Affector369
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
    }
}
