system Frozen
{
    category                                    Sumwars
    technique Frozen_1
    {
        material                                Aureola
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point 
        {
            emission_rate                       2
            angle                               0
            time_to_live                        4.2
            velocity                            1
            position                            0 -0.4 0
            colour                              0.4 0.7 1 1
        }
        affector                                LinearForce 
        {
            force_vector                        0 10 0
        }
        affector                                TextureRotator Affector77
        {
            rotation                            dyn_random
            {
                min                             1
                max                             4
            }
            rotation_speed                      1
        }
        affector                                Colour Affector81
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.186957  1 1 1 1
            time_colour                         0.63913  1 1 1 1
            time_colour                         1    1 1 1 0
            colour_operation                    multiply
        }
    }
}
