system Windwalk
{
    category                                    Sumwars
    technique 
    {
        material                                flareAlpha
        default_particle_width                  0.4
        default_particle_height                 0.4
        default_particle_depth                  0.4
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       275
            angle                               30
            time_to_live                        0.1
            velocity                            dyn_random
            {
                min                             1
                max                             2
            }
            position                            0 1 0
            start_colour_range                  1 1 0.95 1
            box_width                           0.8
            box_height                          2.4
            box_depth                           0.8
        }
    }
}
