#include "action.h"

Action::ActionInfo Action::m_base_info[192];

std::map<std::string, Action::ActionType> Action::m_enum_string_to_type;

void Action::init()
{
	DEBUG5("initialising actions");
	Action::ActionInfo* a;


	a = &(Action::m_base_info[Action::NOACTION]);
	a->m_timer_nr=0;
	a->m_standard_time=2000;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=-1;
	a->m_distance = SELF;
	a->m_flags =0;
	a->m_name = "keine Aktion";
	a->m_req_level = 0;
	a->m_req_ability[0]= Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_noaction";
	a->m_enum_name = "noaction";
	a->m_animation[NO_WEAPON].push_back("idle");
	a->m_animation[ONE_HANDED].push_back("idle");
	a->m_animation[TWO_HANDED].push_back("idle");


	a = &(Action::m_base_info[Action::DIE]);
	a->m_timer_nr=0;
	a->m_standard_time=1000;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=-1;
	a->m_distance = SELF;
	a->m_flags =0;
	a->m_name = "Sterben";
	a->m_req_level = 0;
	a->m_req_ability[0]= Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_die";
	a->m_enum_name = "die";
	a->m_animation[NO_WEAPON].push_back("die");
	a->m_animation[ONE_HANDED].push_back("die");
	a->m_animation[TWO_HANDED].push_back("die");


	a = &(Action::m_base_info[Action::WALK]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::WALK;
	a->m_critical_perc=-1;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Laufen";
	a->m_req_level = 0;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_walk";
	a->m_enum_name = "walk";
	a->m_animation[NO_WEAPON].push_back("walkOneHand");
	a->m_animation[ONE_HANDED].push_back("walkOneHand");
	a->m_animation[TWO_HANDED].push_back("walkOneHand");

	a = &(Action::m_base_info[Action::TAKE_ITEM]);
	a->m_timer_nr=0;
	a->m_standard_time=20;
	a->m_timer=0;
	a->m_base_action = Action::WALK;
	a->m_critical_perc=0.7;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Item aufheben";
	a->m_req_level = 0;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_take_item";
	a->m_enum_name = "take_item";

	a = &(Action::m_base_info[Action::ATTACK]);
	a->m_timer_nr=0;
	a->m_standard_time=1;
	a->m_timer=0;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Angriff";
	a->m_req_level = 0;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_attack";
	a->m_enum_name = "attack";
	a->m_animation[NO_WEAPON].push_back("attackUnarmed");
	a->m_animation[ONE_HANDED].push_back("attack");
	a->m_animation[TWO_HANDED].push_back("attackTwoHands");

	a = &(Action::m_base_info[Action::RANGE_ATTACK]);
	a->m_timer_nr=0;
	a->m_standard_time=1;
	a->m_timer=0;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Distanz Angriff";
	a->m_req_level = 0;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_range_attack";
	a->m_enum_name = "range_attack";
    a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::MAGIC_ATTACK]);
	a->m_timer_nr=0;
	a->m_standard_time=1;
	a->m_timer=0;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.5;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Magischer Angriff";
	a->m_req_level = 0;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_magic_attack";
	a->m_enum_name = "magic_attack";
    a->m_animation[NO_WEAPON].push_back("attackMagicUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackMagicOneHand");
	a->m_animation[TWO_HANDED].push_back("attackMagicTwoHands");

	a = &(Action::m_base_info[Action::HOLY_ATTACK]);
	a->m_timer_nr=0;
	a->m_standard_time=1;
	a->m_timer=0;
	a->m_base_action = Action::HOLY_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Heiliger Angriff";
	a->m_req_level = 0;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_holy_attack";
	a->m_enum_name = "holy_attack";
	a->m_animation[NO_WEAPON].push_back("attackUnarmed");
	a->m_animation[ONE_HANDED].push_back("attack");
	a->m_animation[TWO_HANDED].push_back("attackTwoHands");

	// Faehigkeiten des Kriegers
	a = &(Action::m_base_info[Action::BASH]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=2000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Harter Schlag";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_bash";
	a->m_enum_name = "bash";

	a = &(Action::m_base_info[Action::HAMMER_BASH]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=2000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Hammerschlag";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::AROUND_BLOW;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_hammer_bash";
	a->m_enum_name = "hammer_bash";

	a = &(Action::m_base_info[Action::AROUND_BLOW]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=3000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Rundumschlag";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::BASH;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_around_blow";
	a->m_enum_name = "around_blow";

	a = &(Action::m_base_info[Action::WHIRL_BLOW]);
	a->m_timer_nr=1;
	a->m_standard_time=1.5;
	a->m_timer=3000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Wirbelschlag";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::AROUND_BLOW;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_whirl_blow";
	a->m_enum_name = "whirl_blow";

	a = &(Action::m_base_info[Action::SMASH]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=3000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Schmetterschlag";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::HAMMER_BASH;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_smash";
	a->m_enum_name = "smash";

	a = &(Action::m_base_info[Action::HATE_MAGE]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=4000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Magierhass";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::BASH;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_hate_mage";
	a->m_enum_name = "hate_mage";


	a = &(Action::m_base_info[Action::CHARGE]);
	a->m_timer_nr=1;
	a->m_standard_time=0.5;
	a->m_timer=6000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Sturmangriff";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::BASH;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_charge";
	a->m_enum_name = "charge";

	a = &(Action::m_base_info[Action::STORM_CHARGE]);
	a->m_timer_nr=1;
	a->m_standard_time=0.5;
	a->m_timer=6000;
	a->m_base_action = Action::ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =0;
	a->m_name = "Sturmsense";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::CHARGE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_storm_charge";
	a->m_enum_name = "storm_charge";

	a = &(Action::m_base_info[Action::DECOY]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=150000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Koeder";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_decoy";
	a->m_enum_name = "decoy";

	a = &(Action::m_base_info[Action::SCARE]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=150000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Herausforderung";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::DECOY;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_scare";
	a->m_enum_name = "scare";

	a = &(Action::m_base_info[Action::FIRESWORD]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=240000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Feuer und Schwert";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_firesword";
	a->m_enum_name = "firesword";

	a = &(Action::m_base_info[Action::FLAMESWORD]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=240000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Flammenpakt";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::FLAMEARMOR;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_flamesword";
	a->m_enum_name = "flamesword";

	a = &(Action::m_base_info[Action::FLAMEARMOR]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=300000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Flammenruestung";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::FIRESWORD;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_flamearmor";
	a->m_enum_name = "flamearmor";

	a = &(Action::m_base_info[Action::BERSERK]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=200000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Kampfschrei";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::DECOY;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_berserk";
	a->m_enum_name = "berserk";

	a = &(Action::m_base_info[Action::WARCRY]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=200000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Kriegsschrei";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::BERSERK;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_warcry";
	a->m_enum_name = "warcry";

	a = &(Action::m_base_info[Action::REGENERATE]);
	a->m_timer_nr=2;
	a->m_standard_time=1001;
	a->m_timer=200000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =0;
	a->m_name = "Regeneration";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_regenerate";
	a->m_enum_name = "regenerate";

	a = &(Action::m_base_info[Action::ANGER]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=300000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =0;
	a->m_name = "Barbarische Wut";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::REGENERATE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_anger";
	a->m_enum_name = "anger";

	a = &(Action::m_base_info[Action::FURY]);
	a->m_timer_nr=2;
	a->m_standard_time=500;
	a->m_timer=200000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =0;
	a->m_name = "Barbarische Kraft";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::ANGER;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_fury";
	a->m_enum_name = "fury";

	a = &(Action::m_base_info[Action::STEADFAST]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Turm in der Schlacht";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_steadfast";
	a->m_enum_name = "steadfast";

	a = &(Action::m_base_info[Action::BLOCK]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Blocken";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::STEADFAST;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_block";
	a->m_enum_name = "block";

	a = &(Action::m_base_info[Action::WEAPONMASTER]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Waffenmeister";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::BLOCK;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_weaponmaster";
	a->m_enum_name = "weaponmaster";

	a = &(Action::m_base_info[Action::MONSTER_HUNTER]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Monsterjaeger";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::STEADFAST;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_monster_hunter";
	a->m_enum_name = "monster_hunter";

	a = &(Action::m_base_info[Action::MONSTER_SLAYER]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Monsterschlaechter";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::MONSTER_HUNTER;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_monster_slayer";
	a->m_enum_name = "monster_slayer";

	a = &(Action::m_base_info[Action::ENDURANCE]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Ausdauer";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::MONSTER_SLAYER;
	a->m_req_ability[1] = Action::WEAPONMASTER;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_endurance";
	a->m_enum_name = "endurance";


	// Faehigkeiten des Magiers
	a = &(Action::m_base_info[Action::FIRE_BOLT]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=4000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Feuerblitz";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_fire_bolt";
	a->m_enum_name = "fire_bolt";
    a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::FIRE_STRIKE]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=4000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Feuerschlag";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::FIRE_BOLT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_fire_strike";
	a->m_enum_name = "fire_strike";
    a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::FIRE_WAVE]);
	a->m_timer_nr=2;
	a->m_standard_time=1301;
	a->m_timer=15000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Feuerwelle";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::FIRE_BALL;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_fire_wave";
	a->m_enum_name = "fire_wave";
    a->m_animation[NO_WEAPON].push_back("castMagicStrong");
	a->m_animation[ONE_HANDED].push_back("castMagicStrong");
	a->m_animation[TWO_HANDED].push_back("castMagicStrong");

	a = &(Action::m_base_info[Action::FIRE_STORM]);
	a->m_timer_nr=2;
	a->m_standard_time=1301;
	a->m_timer=15000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Feuersturm";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::FIRE_WAVE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_fire_storm";
	a->m_enum_name = "fire_storm";
	a->m_animation[NO_WEAPON].push_back("castMagicStrong");
	a->m_animation[ONE_HANDED].push_back("castMagicStrong");
	a->m_animation[TWO_HANDED].push_back("castMagicStrong");

	a = &(Action::m_base_info[Action::FIRE_BALL]);
	a->m_timer_nr=1;
	a->m_standard_time=1001;
	a->m_timer=6000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Feuerball";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::FIRE_BOLT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_fire_ball";
	a->m_enum_name = "fire_ball";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::INFERNO_BALL]);
	a->m_timer_nr=1;
	a->m_standard_time=1001;
	a->m_timer=6000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Infernoball";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::FIRE_BALL;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_inferno_ball";
	a->m_enum_name = "inferno_ball";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::FIRE_WALL]);
	a->m_timer_nr=2;
	a->m_standard_time=1001;
	a->m_timer=12000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Feuersaeule";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::FIRE_STRIKE;
	a->m_req_ability[1] = Action::FIRE_BALL;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_fire_wall";
	a->m_enum_name = "fire_wall";
	a->m_animation[NO_WEAPON].push_back("castMagicStrong");
	a->m_animation[ONE_HANDED].push_back("castMagicStrong");
	a->m_animation[TWO_HANDED].push_back("castMagicStrong");

	a = &(Action::m_base_info[Action::INFLAME]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Entzuenden";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_inflame";
	a->m_enum_name = "inflame";

	a = &(Action::m_base_info[Action::ICE_BOLT]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=4000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Eiszapfen";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_ice_bolt";
	a->m_enum_name = "ice_bolt";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");


	a = &(Action::m_base_info[Action::ICE_SPIKE]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=4000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Eisspeer";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::ICE_BOLT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_ice_spike";
	a->m_enum_name = "ice_spike";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::SNOW_STORM]);
	a->m_timer_nr=2;
	a->m_standard_time=1401;
	a->m_timer=14000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Schneesturm";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::FREEZE;
	a->m_req_ability[1] = Action::ICE_RING;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_snow_storm";
	a->m_enum_name = "snow_storm";
	a->m_animation[NO_WEAPON].push_back("castMagicStrong");
	a->m_animation[ONE_HANDED].push_back("castMagicStrong");
	a->m_animation[TWO_HANDED].push_back("castMagicStrong");

	a = &(Action::m_base_info[Action::BLIZZARD]);
	a->m_timer_nr=2;
	a->m_standard_time=1401;
	a->m_timer=14000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Blizzard";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::FROST_RING;
	a->m_req_ability[1] = Action::SNOW_STORM;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_blizzard";
	a->m_enum_name = "blizzard";
	a->m_animation[NO_WEAPON].push_back("castMagicStrong");
	a->m_animation[ONE_HANDED].push_back("castMagicStrong");
	a->m_animation[TWO_HANDED].push_back("castMagicStrong");

	a = &(Action::m_base_info[Action::ICE_RING]);
	a->m_timer_nr=1;
	a->m_standard_time=1001;
	a->m_timer=7000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Eisring";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::ICE_BOLT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_ice_ring";
	a->m_enum_name = "ice_ring";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::FROST_RING]);
	a->m_timer_nr=1;
	a->m_standard_time=1001;
	a->m_timer=7000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Frostring";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::ICE_RING;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_frost_ring";
	a->m_enum_name = "frost_ring";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::FREEZE]);
	a->m_timer_nr=2;
	a->m_standard_time=1001;
	a->m_timer=11000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Einfrieren";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::ICE_BOLT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_freeze";
	a->m_enum_name = "freeze";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::CHILL]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Klirrende Kaelte";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_chill";
	a->m_enum_name = "chill";

	a = &(Action::m_base_info[Action::LIGHTNING]);
	a->m_timer_nr=1;
	a->m_standard_time=501;
	a->m_timer=4000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Blitz";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_lightning";
	a->m_enum_name = "lightning";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::LIGHTNING_STRIKE]);
	a->m_timer_nr=1;
	a->m_standard_time=501;
	a->m_timer=4000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Blitzschlag";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::LIGHTNING;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_lightning_strike";
	a->m_enum_name = "lightning_strike";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::THUNDERSTORM]);
	a->m_timer_nr=2;
	a->m_standard_time=1301;
	a->m_timer=12000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Gewitter";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::LIGHTNING_STRIKE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_thunderstorm";
	a->m_enum_name = "thunderstorm";
	a->m_animation[NO_WEAPON].push_back("castMagicStrong");
	a->m_animation[ONE_HANDED].push_back("castMagicStrong");
	a->m_animation[TWO_HANDED].push_back("castMagicStrong");

	a = &(Action::m_base_info[Action::THUNDERSTORM2]);
	a->m_timer_nr=2;
	a->m_standard_time=1301;
	a->m_timer=12000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Blitzgewitter";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::THUNDERSTORM;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_thunderstorm2";
	a->m_enum_name = "thunderstorm2";
	a->m_animation[NO_WEAPON].push_back("castMagicStrong");
	a->m_animation[ONE_HANDED].push_back("castMagicStrong");
	a->m_animation[TWO_HANDED].push_back("castMagicStrong");

	a = &(Action::m_base_info[Action::CHAIN_LIGHTNING]);
	a->m_timer_nr=1;
	a->m_standard_time=801;
	a->m_timer=7000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Kettenblitz";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::LIGHTNING;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_chain_lightning";
	a->m_enum_name = "chain_lightning";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::CHAIN_LIGHTNING2]);
	a->m_timer_nr=1;
	a->m_standard_time=801;
	a->m_timer=7000;
	a->m_base_action = Action::MAGIC_ATTACK;
	a->m_critical_perc=0.8;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Kugelblitz";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::CHAIN_LIGHTNING;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_chain_lightning2";
	a->m_enum_name = "chain_lightning2";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::STATIC_SHIELD]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=40000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.8;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Statikschild";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::CHAIN_LIGHTNING;
	a->m_req_ability[1] = Action::LIGHTNING_STRIKE;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_static_shield";
	a->m_enum_name = "static_shield";
	a->m_animation[NO_WEAPON].push_back("castMagicWeak");
	a->m_animation[ONE_HANDED].push_back("castMagicWeak");
	a->m_animation[TWO_HANDED].push_back("castMagicWeak");

	a = &(Action::m_base_info[Action::IONISATION]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Ionisierung";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_ionisation";
	a->m_enum_name = "ionisation";


	// Schuetze Faehigkeiten
	a = &(Action::m_base_info[Action::TRIPLE_SHOT]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=3000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.3;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "1 Vogel mit 3 Steinen";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_triple_shot";
	a->m_enum_name = "triple_shot";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");


	a = &(Action::m_base_info[Action::GUIDED_TRIPLE_SHOT]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=3000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.3;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Todesschwarm";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::MULTISHOT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_guided_triple_shot";
	a->m_enum_name = "guided_triple_shot";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::MULTISHOT]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=5000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.7;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Faecherschuss";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::TRIPLE_SHOT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_multishot";
	a->m_enum_name = "multishot";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::VOLLEY_SHOT]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=5000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.7;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Eisenhagel";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::MULTISHOT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_volley_shot";
	a->m_enum_name = "volley_shot";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::PIERCE]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=3000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Elfenwanderer";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::TRIPLE_SHOT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_pierce";
	a->m_enum_name = "pierce";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::WEAK_POINT]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=4000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "wunder Punkt";
	a->m_req_level = 2;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_weak_point";
	a->m_enum_name = "weak_point";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::BLIND_RAGE]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=4000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "blinde Wut";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::WEAK_POINT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_blind_rage";
	a->m_enum_name = "blind_rage";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::VACUUM]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=6000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Vakuum";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_vacuum";
	a->m_enum_name = "vacuum";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::DEATH_ROULETTE]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=3000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Todesroulette";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::GUIDED_TRIPLE_SHOT;
	a->m_req_ability[1] = Action::VOLLEY_SHOT;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_death_roulette";
	a->m_enum_name = "death_roulette";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::EXPLODING_ARROW]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=7000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Sprengpfeil";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_exploding_arrow";
	a->m_enum_name = "exploding_arrow";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[Action::EXPLOSION_CASCADE]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=7000;
	a->m_base_action = Action::RANGE_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =0;
	a->m_name = "Sprengkaskade";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::EXPLODING_ARROW;
	a->m_req_ability[1] = Action::MULTISHOT;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_exploding_cascade";
	a->m_enum_name = "exploding_cascade";
	a->m_animation[NO_WEAPON].push_back("attackRangedUnarmed");
	a->m_animation[ONE_HANDED].push_back("attackRangedUnarmed");
	a->m_animation[TWO_HANDED].push_back("attackRangedBow");

	a = &(Action::m_base_info[AIMED_SHOT]);
	a->m_timer_nr=2;
	a->m_standard_time=801;
	a->m_timer=140000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = SELF;
	a->m_flags =0;
	a->m_name = "Zielschuss";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_aimed_shot";
	a->m_enum_name = "aimed_shot";

	a = &(Action::m_base_info[BOW_SPIRIT]);
	a->m_timer_nr=2;
	a->m_standard_time=801;
	a->m_timer=140000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = SELF;
	a->m_flags =0;
	a->m_name = "Bogenseele";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::AIMED_SHOT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_bow_spirit";
	a->m_enum_name = "bow_spirit";

	a = &(Action::m_base_info[ICE_ARROWS]);
	a->m_timer_nr=2;
	a->m_standard_time=801;
	a->m_timer=240000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Eispfeil";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_ice_arrows";
	a->m_enum_name = "ice_arrows";
	a->m_animation[NO_WEAPON].push_back("magicArrow");
	a->m_animation[ONE_HANDED].push_back("magicArrow");
	a->m_animation[TWO_HANDED].push_back("magicArrow");

	a = &(Action::m_base_info[FREEZING_ARROWS]);
	a->m_timer_nr=2;
	a->m_standard_time=801;
	a->m_timer=240000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Frostpfeile";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::ICE_ARROWS;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_freezing_arrows";
	a->m_enum_name = "freezing_arrows";
	a->m_animation[NO_WEAPON].push_back("magicArrow");
	a->m_animation[ONE_HANDED].push_back("magicArrow");
	a->m_animation[TWO_HANDED].push_back("magicArrow");

	a = &(Action::m_base_info[WIND_ARROWS]);
	a->m_timer_nr=2;
	a->m_standard_time=801;
	a->m_timer=240000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Windpfeile";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_wind_arrows";
	a->m_enum_name = "wind_arrows";
	a->m_animation[NO_WEAPON].push_back("magicArrow");
	a->m_animation[ONE_HANDED].push_back("magicArrow");
	a->m_animation[TWO_HANDED].push_back("magicArrow");

	a = &(Action::m_base_info[STORM_ARROWS]);
	a->m_timer_nr=2;
	a->m_standard_time=801;
	a->m_timer=240000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Sturmpfeile";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::WIND_ARROWS;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_storm_arrows";
	a->m_enum_name = "storm_arrows";
	a->m_animation[NO_WEAPON].push_back("magicArrow");
	a->m_animation[ONE_HANDED].push_back("magicArrow");
	a->m_animation[TWO_HANDED].push_back("magicArrow");

	a = &(Action::m_base_info[WIND_WALK]);
	a->m_timer_nr=2;
	a->m_standard_time=801;
	a->m_timer=60000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = SELF;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Windwandern";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::AIMED_SHOT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_wind_walk";
	a->m_enum_name = "wind_walk";

	a = &(Action::m_base_info[Action::EVADE]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Katzenreflexe";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_evade";
	a->m_enum_name = "evade";

	a = &(Action::m_base_info[Action::CRITICAL_STRIKE]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Elfenaugen";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::EVADE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_critical_strike";
	a->m_enum_name = "critical_strike";

	a = &(Action::m_base_info[Action::CONCENTRATION]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Konzentration";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::EVADE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_concentration";
	a->m_enum_name = "concentration";

	a = &(Action::m_base_info[Action::MENTAL_WALL]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Geistige Wand";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::CONCENTRATION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_mental_wall";
	a->m_enum_name = "mental_wall";

	a = &(Action::m_base_info[Action::RESIST_ICE]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Nordwanderer";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_resist_ice";
	a->m_enum_name = "resist_ice";

	a = &(Action::m_base_info[Action::RESIST_AIR]);
	a->m_timer_nr=0;
	a->m_standard_time=0;
	a->m_timer=0;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.0;
	a->m_distance = PASSIVE;
	a->m_flags =0;
	a->m_name = "Nordjaeger";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::RESIST_ICE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_resist_air";
	a->m_enum_name = "resist_air";


	// Priester Faehigkeiten
	a = &(Action::m_base_info[HOLY_LIGHT]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=4000;
	a->m_base_action = Action::HOLY_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "leuchtender Schlag";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_holy_light";
	a->m_enum_name = "holy_light";

	a = &(Action::m_base_info[HOLY_FIRE]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=4000;
	a->m_base_action = Action::HOLY_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "geweihter Schlag";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::HOLY_LIGHT;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_holy_fire";
	a->m_enum_name = "holy_fire";

	a = &(Action::m_base_info[BURNING_RAGE]);
	a->m_timer_nr=2;
	a->m_standard_time=1001;
	a->m_timer=180000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "brennende Wut";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::BLAZING_SHIELD;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_burning_rage";
	a->m_enum_name = "burning_rage";

	a = &(Action::m_base_info[CURE_BLIND_MUTE]);
	a->m_timer_nr=1;
	a->m_standard_time=501;
	a->m_timer=3000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "sanftes Leuchten";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_cure_blind_mute";
	a->m_enum_name = "cure_blind_mute";

	a = &(Action::m_base_info[CURE_BLIND_MUTE_PARTY]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=6000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "allessehendes Auge";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::CURE_BLIND_MUTE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_cure_blind_mute_party";
	a->m_enum_name = "cure_blind_mute_party";

	a = &(Action::m_base_info[BLAZING_SHIELD]);
	a->m_timer_nr=2;
	a->m_standard_time=1001;
	a->m_timer=160000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "lodernder Schild";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_blazing_shield";
	a->m_enum_name = "blazing_shield";

	a = &(Action::m_base_info[LIGHT_BEAM]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=3000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "gleissendes Licht";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_light_beam";
	a->m_enum_name = "light_beam";

	a = &(Action::m_base_info[BURNING_SUN]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=7000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "blendende Sonne";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::LIGHT_BEAM;
	a->m_req_ability[1] = Action::CURE_BLIND_MUTE;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_burning_sun";
	a->m_enum_name = "burning_sun";

	a = &(Action::m_base_info[BREAK_BINDING]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=4000;
	a->m_base_action = Action::HOLY_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "zerbrechender Schlag";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_break_binding";
	a->m_enum_name = "break_binding";

	a = &(Action::m_base_info[DISRUPT_BINDING]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=4000;
	a->m_base_action = Action::HOLY_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "aufl�sender Schlag";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::BREAK_BINDING;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_disrupt_binding";
	a->m_enum_name = "disrupt_binding";

	a = &(Action::m_base_info[MAGIC_SHIELD]);
	a->m_timer_nr=2;
	a->m_standard_time=1001;
	a->m_timer=200000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "magischer Schild";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::BLAZING_SHIELD;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_magic_shield";
	a->m_enum_name = "magic_shield";

	a = &(Action::m_base_info[CURE_POIS_BURN]);
	a->m_timer_nr=1;
	a->m_standard_time=501;
	a->m_timer=3000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Schmerz lindern";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::HEAL;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_cure_pois_burn";
	a->m_enum_name = "cure_pois_burn";

	a = &(Action::m_base_info[CURE_POIS_BURN_PARTY]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=6000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "heilendes Wasser";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::CURE_BLIND_MUTE;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_cure_pois_burn_party";
	a->m_enum_name = "cure_pois_burn_party";

	a = &(Action::m_base_info[ACID]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=5000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Saeure";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::CURE_POIS_BURN;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_acid";
	a->m_enum_name = "acid";

	a = &(Action::m_base_info[HEAL]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=5000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Heilung";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_heal";
	a->m_enum_name = "heal";

	a = &(Action::m_base_info[HEAL_PARTY]);
	a->m_timer_nr=2;
	a->m_standard_time=701;
	a->m_timer=10000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Grosse Heilung";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::CURE_POIS_BURN;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_heal_party";
	a->m_enum_name = "heal_party";

	a = &(Action::m_base_info[DIVINE_WIND]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=3000;
	a->m_base_action = Action::HOLY_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Windschlag";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_divine_wind";
	a->m_enum_name = "divine_wind";

	a = &(Action::m_base_info[DIVINE_STORM]);
	a->m_timer_nr=1;
	a->m_standard_time=1;
	a->m_timer=6000;
	a->m_base_action = Action::HOLY_ATTACK;
	a->m_critical_perc=0.66;
	a->m_distance = MELEE;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Goettlicher Schlag";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::DIVINE_WIND;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_divine_storm";
	a->m_enum_name = "divine_storm";

	a = &(Action::m_base_info[BLADE_STORM]);
	a->m_timer_nr=2;
	a->m_standard_time=1001;
	a->m_timer=160000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Klingensturm";
	a->m_req_level = 1;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_blade_storm";
	a->m_enum_name = "blade_storm";

	a = &(Action::m_base_info[CURE_CONF_BSRK]);
	a->m_timer_nr=1;
	a->m_standard_time=501;
	a->m_timer=3000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Konzentration wiederherstellen";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::NOACTION;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_cure_conf_bsrk";
	a->m_enum_name = "cure_conf_bsrk";

	a = &(Action::m_base_info[CURE_CONF_BSRK_PARTY]);
	a->m_timer_nr=2;
	a->m_standard_time=501;
	a->m_timer=6000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Seelenschild";
	a->m_req_level = 40;
	a->m_req_ability[0] = Action::CURE_CONF_BSRK;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_cure_conf_bsrk_party";
	a->m_enum_name = "cure_conf_bsrk_party";

	a = &(Action::m_base_info[HYPNOSIS]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=4000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "Hypnose";
	a->m_req_level = 20;
	a->m_req_ability[0] = Action::CURE_CONF_BSRK;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_hypnosis";
	a->m_enum_name = "hypnosis";

	a = &(Action::m_base_info[HYPNOSIS2]);
	a->m_timer_nr=1;
	a->m_standard_time=701;
	a->m_timer=7000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = RANGED;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "hypnotischer Wirbel";
	a->m_req_level = 60;
	a->m_req_ability[0] = Action::HYPNOSIS;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_hypnosis2";
	a->m_enum_name = "hypnosis2";

	a = &(Action::m_base_info[KEEN_MIND]);
	a->m_timer_nr=2;
	a->m_standard_time=701;
	a->m_timer=180000;
	a->m_base_action = Action::NOACTION;
	a->m_critical_perc=0.66;
	a->m_distance = PARTY_MULTI;
	a->m_flags =MUTE_AFFECTED;
	a->m_name = "messerscharfer Geist";
	a->m_req_level = 5;
	a->m_req_ability[0] = Action::BLADE_STORM;
	a->m_req_ability[1] = Action::NOACTION;
	a->m_req_ability[2] = Action::NOACTION;
	a->m_description = "descr_keen_mind";
	a->m_enum_name = "keen_mind";

	for (int i =0;i<192;i++)
	{
		a = &(Action::m_base_info[(ActionType) i]);
		if (a->m_enum_name != "")
		{
			m_enum_string_to_type.insert(make_pair(a->m_enum_name,(ActionType) i));
		}
	}
}


string Action::getName(ActionType type)
{
    #ifndef WIN32
        return ( gettext((m_base_info[type].m_enum_name).c_str()) );
    #else
        return m_base_info[type].m_enum_name;
    #endif
}


string Action::getDescription(ActionType type)
{
    #ifndef WIN32
        return ( gettext((m_base_info[type].m_description).c_str()) );
    #else
        return m_base_info[type].m_description;
    #endif
}

void Action::toString(CharConv* cv)
{

	cv->toBuffer((short) m_type);
	cv->toBuffer(m_time);
	cv->toBuffer((char) m_action_equip);
	cv->toBuffer(m_animation_number);
	cv->toBuffer(m_elapsed_time);


}

void Action::fromString(CharConv* cv)
{
	short tmp;
	char ctmp;
	cv->fromBuffer(tmp);
	m_type = (ActionType) tmp;
	cv->fromBuffer(m_time);
	cv->fromBuffer(ctmp);
	m_action_equip = (ActionEquip) ctmp;
	cv->fromBuffer(m_animation_number);
	cv->fromBuffer(m_elapsed_time);
}

